<?php
/**
 * Ornek blog yazilari (istanbulpaletci.com blogundaki uc yazi).
 *
 * Saf dizi dondurur; WordPress fonksiyonlarina bagimli degildir. Manifest
 * her yazi icin paneldeki gizli sayfanin varsayilan metinlerini buradan
 * alir (content-manifest.php). Yazilarin kendisini ilk kurulum betigi
 * olusturur (scripts/data/istanbulpaletci-posts.php); metinler onunla
 * birebir aynidir.
 *
 * Metin bicimi: bos satir paragraf ayirir. '## ' ile baslayan blok ara
 * baslik, her satiri '- ' ile baslayan blok madde listesidir.
 */

return array(
	array(
		'slug'    => '2022-guncel-palet-fiyatlari-nedir',
		'title'   => '2022 Güncel Palet Fiyatları Nedir?',
		'excerpt' => 'Güncel palet fiyatları, günden güne ekonomideki farklılıklardan ötürü değişkenlik gösterebilmektedir. Palet fiyatları ebat ve malzeme çeşidine göre farklılıklar göstermekle birlikte uygun seçenekli ikinci el paletler de bulunmaktadır. Bu yüzden firmamız ile iletişime geçmeniz hâlinde size en uygun paletin ve palet çeşitlerinin fiyatını öğrenebilir, ardından paletinizi satın alabilirsiniz.',
		'body'    => "Güncel palet fiyatları, günden güne ekonomideki farklılıklardan ötürü değişkenlik gösterebilmektedir. Palet fiyatları ebat ve malzeme çeşidine göre farklılıklar göstermekle birlikte uygun seçenekli ikinci el paletler de bulunmaktadır. Bu yüzden firmamız ile iletişime geçmeniz hâlinde size en uygun paletin ve palet çeşitlerinin fiyatını öğrenebilir, ardından paletinizi satın alabilirsiniz.\n\n2022 güncel palet fiyatları talep ile orantılı olarak değişkenlik göstermemektedir. Fiyatlar sabittir fakat sıfır paletler ikinci el paletlere göre biraz daha yüksek fiyatta olabilir. Sıfır üretim paletler daha temiz ve sağlam oldukları için kullanım konusunda hiçbir problem yaşamadan sürecinizi devam ettirmenize yardımcı olur.\n\nPalet fiyatlarını etkileyen tek etken güncel ekonomik durumdur. Güncel ekonomik durum hem sıfır palet fiyatlarını hem de ikinci el palet fiyatlarını oldukça etkilemiştir. Üretim ve sanayileşme günden güne arttıkça sanayi paletine ihtiyaç da aynı oranda artmaktadır.\n\nPalet fiyatları ithalata da bağlıdır. Son dönemlerde döviz fiyatlarındaki belirsizlik ahşap palet fiyatlarını da etkileyen bir faktör hâline gelmiştir. Bu sebepten ithalat alanında azalmalar meydana gelmektedir. İthalatın azalması ikinci el paletin dönüştürülmesini etkileyerek mevcut palet sayısının azalmasına sebep olmuştur.\n\nSize en uygun palet fiyatını firmamızla iletişime geçerek öğrenebilir, dilediğiniz ölçülerdeki paletleri sıfır veya ikinci el olarak uygun fiyatla temin edebilirsiniz.\n\n## Palet seçerken fiyatı ne belirler?\n\nOldukça uygun fiyatlardan başlayan palet seçeneklerinden size en uygun olan paletin alımını gerçekleştirebilirsiniz. Paletlerin kalitesi ve kullanım alanları fiyatı etkilemektedir. Satın alacağınız paletin özelliklerinin fiyatını etkileyeceğini belirtmek isteriz.\n\nBütün palet çeşitlerinin ve bütün ölçülerdeki paletlerin üretimini gerçekleştirdiğimiz fabrikamızda size en uygun paletlerden yana tercihinizi kullanabilirsiniz. Paletlerde birçok çeşit olduğu için fiyatlar farklılık gösterebilir.\n\nÇivisi, kerestesi ve üretiminde kullanılan tüm malzemeler kaliteli ürünlerdir. Kullanacağınız alanı belirterek bu alana en uygun palet seçimini birlikte yapabiliriz. Tüm palet çeşitlerimiz, uzun yıllar sorunsuz kullanmanız amacıyla özenle hazırlanır.",
		'date'    => '2022-05-11 10:00:00',
	),
	array(
		'slug'    => 'sanayi-paletleri-kullanim-alanlari-nelerdir',
		'title'   => 'Sanayi Paletleri Kullanım Alanları Nelerdir?',
		'excerpt' => 'Hacim olarak yüksek tonajlı malzeme veya ürünlerin taşınmasında genellikle sanayi paletleri kullanılmaktadır. Ayrıca sanayi paletleri, firmaların depolarında nakil için bekleyen malların düzgün bir şekilde istiflenmesi ve fazla yer kaplamaması için kullanılmaktadır. Paletler ile sarılan ürünler yere temas etmedikleri için nemden uzaklaşarak temiz ve kuru kalırlar.',
		'body'    => "Hacim olarak yüksek tonajlı malzeme veya ürünlerin taşınmasında genellikle sanayi paletleri kullanılmaktadır. Ayrıca sanayi paletleri, firmaların depolarında nakil için bekleyen malların düzgün bir şekilde istiflenmesi ve fazla yer kaplamaması için kullanılmaktadır. Paletler ile sarılan ürünler yere temas etmedikleri için nemden uzaklaşarak temiz ve kuru kalırlar.\n\nNakliyat, ihracat, ithalat ve depolama gerektiren tüm sektörlerde ahşap paletlerin kullanımı yaygındır. Ahşap paletler dayanıklılık konusunda oldukça verimlidir ve korozyona uğrama oranları düşüktür. Hem yurt içinde hem de yurt dışında satılan malların nakliyatı sırasında ürünlerin zarar görmeden varacağı noktaya ulaştırılması için ahşap palet kullanımı önemli bir yer tutar.\n\nGenellikle ahşap paletler paketlerin alt ve üst kısmına konulur. Ardından çelik veya plastik şeritlerle etrafı sarılır. Daha sonra naylon veya naylon benzeri bir malzeme ile tamamının sarılması sağlanır.\n\n## Artan üretim, artan palet ihtiyacı\n\nGelişen teknoloji ile birlikte üretim günden güne artmaktadır. Artan üretim sanayi alanında hızlı süreçler oluşturduğu için sanayi paleti ihtiyacı da hiç azalmadan sürmektedir. Uzun yıllardan bu yana kullanılan sanayi paletleri; ambalaj ürünlerinin depolanması, nakli ve transferi gibi birçok alanda ürünü koruyan, iş gücünü azaltan bir malzemedir. Sanayi paletlerinde standart ölçülerin yanı sıra özel üretim paletler de imal edilmektedir.\n\n## Depoda istifleme\n\nPaletler, bir ürünü veya malzemeyi depoya istiflerken kullanılır. Paletler eşliğinde muhafaza edilen ürünler hem daha az yer kaplar hem de yıkılma, ezilme, kırılma gibi olası problemlerin önüne geçilir. Palet kullanılarak üst üste ürün konulabildiği için yerden ve mekândan tasarruf sağlanır; süreç de daha hızlı yönetilir.\n\nPalet eşliğinde muhafaza edilen ürünler forkliftler aracılığıyla kolayca taşınabilir. Forkliftin çatalları paletlere geçirilerek yükün taşınması kolaylaşır. Market, fabrika, gıda ürünleri, elektronik ve yapı ürünlerinde palet kullanmak oldukça avantajlı bir seçenektir.",
		'date'    => '2022-05-11 11:00:00',
	),
	array(
		'slug'    => 'ahsap-palet-nedir-palet-uretimi-sureci-nasildir',
		'title'   => 'Ahşap Palet Nedir? Palet Üretimi Süreci Nasıldır?',
		'excerpt' => 'Günümüzde ahşap paletler, maliyet ve verimlilik açısından sıklıkla tercih edilen palet türlerinden biri hâline gelmiştir. Dünya genelinde palet piyasasında %97 oranında ahşap palet kullanılır. Diğer paletlere oranla maliyeti düşük, kullanımı kolay, geri dönüştürülebilir ve kullanım esnasında daha dayanıklı olduğu için ahşap palet daha fazla tercih edilmektedir.',
		'body'    => "Günümüzde ahşap paletler, maliyet ve verimlilik açısından sıklıkla tercih edilen palet türlerinden biri hâline gelmiştir. Dünya genelinde palet piyasasında %97 oranında ahşap palet kullanılır. Diğer paletlere oranla maliyeti düşük, kullanımı kolay, geri dönüştürülebilir ve kullanım esnasında daha dayanıklı olduğu için ahşap palet daha fazla tercih edilmektedir.\n\n## Ham madde seçimi\n\nAhşap paletler için ham madde seçimi oldukça önemlidir. Ham madde olarak çam, kayın, meşe ağacı ve kavak kütükleri ilk tercihler arasındadır. Uygun ahşaplar seçilerek tomrukların biçilmesiyle paralel parçalar elde edilir ve bu parçalar palet kerestesi olacak şekilde işleme konulur. Bu işlemi tomruk biçme ustaları ve tomruk biçme makineleri yapar.\n\n## Ahşap palet çeşitleri\n\n- Ahşap Euro palet\n- Ahşap ISO palet\n- Ahşap Kuzey Amerika paletleri\n- Ahşap Asya paletleri\n- Ahşap Avustralya paletleri\n- Ahşap CP paletler\n- Ebatsız ahşap paletler (özel ölçülü paletler)\n\nSıraladığımız palet çeşitlerinden Euro paletler, Avrupa Birliği standartlarına uygun paletlerdir. Bu yüzden bütün dünya genelinde ahşap Euro palet tercih edilir. Dünyanın farklı bölgelerinde farklı paletler ve palet ölçüleri bulunur; bu da verimsiz bir üretime sebep olur. Euro palet bu yüzden ortaya çıkmıştır.\n\n## Palet üretim süreci\n\nPalet üretiminde doğru ürünün seçilmesi oldukça önemlidir. Doğru ağaç seçilerek üretilen paletler istenen verimliliğin elde edilmesine yardımcı olur. İşlenerek palet hâline gelmesi ve çivilerle desteklenerek oluşturulması, belirli prosedürler ve uzman ekiplerin kontrolünde gerçekleştirilir.\n\nÖncelikle tomruklar kereste hâline getirilir. Budaklı keresteler ayrıştırılır. Ardından seçilen keresteler ölçüye uygun en ve kalınlıkta işleme alınır. Palet oluşturma aşamasına hazır hâle getirilen keresteler, standartlar eşliğinde üretime alınır. Uzun ömürlü ve dayanıklı palet üretimi için bu aşamalar oldukça önemlidir.",
		'date'    => '2022-05-11 12:00:00',
	),
);
